### ISSUE TITLE
A Movie Question

### ISSUE THREAD

**Issue by zzuwpf** [SPECFEM/specfem3d#1629]
Hi!
I have successfully generated the corresponding visualization file, but when I first tried to open the VTK speed file to see the effect of seismic wave propagation, I found no change. When I played the inp file and then opened the vtk speed file, the results changed quite nicely. What's going on here, please? How can I fix it?

One of the commands I use has the following format：

`./bin/xcreate_movie_shakemap_AVS_DX_GMT`

`./bin/xcombine_vol_data_vtk all velocity_X_it000200 ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 0`

**Comment by ZZU-WPF** [comment]
In addition, I generated each slice file when generating the vtk speed file. For example:
`./bin/xcombine_vol_data_vtk all velocity_X_it000200 ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 0`
`./bin/xcombine_vol_data_vtk all velocity_X_it000400 ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 0`
`./bin/xcombine_vol_data_vtk all velocity_X_it000600 ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 0`
...
Still I meet this situation.

**Comment by danielpeter** [comment]
I'm not sure exactly what you're trying to achieve here, but did you check if the `xcreate_movie_shakemap_AVS_DX_GMT` is outputting the same quantity as the one you're using with the `xcombine_vol_data_vtk`, i.e., velocity in X-direction?

**Comment by zzuwpf** [comment]
> I'm not sure exactly what you're trying to achieve here, but did you check if the `xcreate_movie_shakemap_AVS_DX_GMT` is outputting the same quantity as the one you're using with the `xcombine_vol_data_vtk`, i.e., velocity in X-direction?

I'm sorry I'm a new user of this program. The issue has been resolved, thank you very much for your guidance
