### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by VarunD21029** [SPECFEM/specfem3d#1635]
### Description

I am simulating a point source on the 121 core system. It takes over 26 hrs for time step 0.005 and much less for a bigger fault source. Anyone can give a reason why?

### Affected SPECFEM3D version

Specfem 3d Cartesian

### Your software and hardware environment

Linux Ubuntu

### Reproduction steps

```bash
1. Go to '...'
2. Change settings '....'
3. Use data files '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by danielpeter** [comment]
you have to provide more details on this bug report to become reproducible - closing this report.
