### ISSUE TITLE
#1344 CUDA memory error!

### ISSUE THREAD

**Issue by brioglade** [SPECFEM/specfem3d#1679]
hi 

https://github.com/SPECFEM/specfem3d/issues/1344

~/specfem3d/EXAMPLES/applications/fault_examples/tpv15

This example can't enable GPU true. I use another computer with a relatively large memory, but still encounter the following error.  Although the above example used 32 $NPROCs, it still took about 5 hours. 

CUDA error !!!!! !!!!!
at CUDA call error code: # 2402
Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
Abort(1) on node 3 (rank 3 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
Abort(1) on node 4 (rank 4 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
Abort(1) on node 5 (rank 5 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
Abort(1) on node 6 (rank 6 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6

How to fix it? Thank you very much.

**Comment by danielpeter** [comment]
you need more GPUs... the simulation is too big for your card.
