### ISSUE TITLE
Error running adjoint simulations

### ISSUE THREAD

**Issue by aakash10gupta** [SPECFEM/specfem3d#1680]
### Description

**Error invalid irec for local adjoint source**

I am receiving the above error while trying to run adjoint simulations using the latest master branch. The forward simulation runs fine but the adjoint simulation does not. The output_solver.txt file has no error messages but stops being written out midway. The cluster output log displays the above error message.

After some debugging it looks like the error is being caused by changes to the file [setup_sources_receivers.f90](https://github.com/SPECFEM/specfem3d/blob/master/src/specfem3D/setup_sources_receivers.f90) in the commit [5530249](https://github.com/SPECFEM/specfem3d/commit/55302495e9bcceb639babcf58a4062d20c8f2532). I was able to run adjoint simulations with a commit just prior to this suspected one.

[bf45798](https://github.com/SPECFEM/specfem3d/commit/bf45798f3af9d792326a829de920fd944cf7c7dd) - latest master (FAILS)
[5530249](https://github.com/SPECFEM/specfem3d/commit/55302495e9bcceb639babcf58a4062d20c8f2532) - suspected commit (NOT TESTED)
[172f4ec](https://github.com/SPECFEM/specfem3d/commit/172f4ec0e01e5da7810f095ca6296b8095cc231b) - commit prior to the suspected one (SUCCEEDS)

Files to reproduce the error using the steps mentioned below -
[kernels.zip](https://github.com/SPECFEM/specfem3d/files/14519545/kernels.zip)

### Affected SPECFEM3D version

bf45798f3af9d792326a829de920fd944cf7c7dd (and probably some prior commits as well)

### Your software and hardware environment

HPC cluster - chinook04 (UAF)
icc (ICC) 2021.6.0 20220226
ifort (IFORT) 2021.6.0 20220226

### Reproduction steps

1. Clone latest specfem master branch [bf45798](https://github.com/SPECFEM/specfem3d/commit/bf45798f3af9d792326a829de920fd944cf7c7dd) and compile using `make all`.
2. Also compile [create_adjsrc_traveltime.f90](https://github.com/SPECFEM/specfem3d/blob/master/utils/adjoint_sources/traveltime/create_adjsrc_traveltime.f90) by running `make` in its respective folder, and move the thus created `xcreate_adjsrc_traveltime` to the bin folder.
3. Unzip the above attached zipped folder.
4. Copy compiled specfem bin folder into the unzipped folder.
5. Run the provided `kernels.bash` script on a slurm managed cluster or otherwise.
6. Wait for the job to fail and see error.

### Logs

**Error invalid irec for local adjoint source**

### OS

Rocky Linux 8.7

**Comment by danielpeter** [comment]
good catch, thanks Aakash! should be addressed by PR #1686 - please doublecheck with your example again.

**Comment by aakash10gupta** [comment]
Thanks Daniel! I doublechecked and it's working fine now.
