### ISSUE TITLE
Error: Arithmetic overflow at (1) make: *** [obj/read_stations.spec.o] Error 1

### ISSUE THREAD

**Issue by jxhxb** [SPECFEM/specfem3d#1732]
I want to know how to install the newest specfem3d,i failed as the error that the following.If you have faced the same problem and you have made it done,could you tell me how it done,thank you very much!

![image](https://github.com/user-attachments/assets/8f05f009-5284-4887-bff6-2ea437d2b043)

**Comment by aakash10gupta** [comment]
Hi,

I am assuming that you are using a gfortran compiler. Can you try updating the gfortran compiler you are using and see if that solves the problem?

**Comment by jxhxb** [comment]
> Hi,
> 
> I am assuming that you are using a gfortran compiler. Can you try updating the gfortran compiler you are using and see if that solves the problem?

Thank you! YES,the problem is about gfortran version, when updatiing gcc, you should also remake mpi, or will getting wrong!

**Comment by jxhxb** [comment]
> > Hi,
> > I am assuming that you are using a gfortran compiler. Can you try updating the gfortran compiler you are using and see if that solves the problem?
> 
> Thank you! YES,the problem is about gfortran version, when updatiing gcc, you should also remake mpi, or will getting wrong!

It's better to install gcc versiion>9, i installed gcc 10.2.0, to make sure read_stations.f90 do not appear error!

**Comment by aakash10gupta** [comment]
Ok, that is good to know. Please close the issue if your problem is resolved.
