### ISSUE TITLE
How to set changes after seting another stike angle and dip angle in HETE_fault_properties  

### ISSUE THREAD

**Issue by jxhxb** [SPECFEM/specfem3d#1735]
![image](https://github.com/user-attachments/assets/4550b998-bd08-4acc-88bc-c6e9d3beaa04)
The above picture is the specfem3d-master/EXAMPLES/applications/fault_examples/hete_fault_properties/DATA/ initial file. The picture's top is initial_stress and down is Par_file_fault.

![image](https://github.com/user-attachments/assets/e0675553-7fb1-4698-8f6f-1ba78d58c2d7)
The above picture is wthat i  changged in initial_stress.dat and Par_file_faults , i just changed the positions' information  (after seting stike angle and dip angle), include initial_stress' position and other like on above picture when the stike angle is 90 and dip angle is 90(the specfem3d example is these angles), my module is working correctly. 
![image](https://github.com/user-attachments/assets/09e47413-087c-44e7-869e-fa8d2b3dfb5c)
![image](https://github.com/user-attachments/assets/9659de3e-b8f5-4bda-afc1-de0deb78c512)

But when setting stike angle 45 and dip angle is 85, and calculated all the positions after rotated correctly(stike angle 45 and dip angle is 85), the module doesn't work .
![image](https://github.com/user-attachments/assets/440d8479-a358-4067-852c-ed6036df0cbb)
![image](https://github.com/user-attachments/assets/8b4b3d4c-b958-415d-9d3b-5aa35aa9e2d2)

I want to know if any wrong step occured of my flow? If anyone can help me ,thank you very much!

**Comment by jxhxb** [comment]
this is the cubit fault file
[fault.txt](https://github.com/user-attachments/files/16922431/fault.txt)

`
reset
create cylinder height {80*1000} radius {30*1000}  
${idVol1=Id('volume')}
create planar surface zplane  
${idInt=Id('surface')}

rotate surface {idInt} about Y angle -85.000000   
rotate surface {idInt} about Z angle -45.000000

surface {idInt} move z {-0.00000*1000}  
create planar surface zplane     
${idSur=Id('surface')}

webcut volume {idVol1} with sheet extended from surface {idSur}  
${idVol2=Id('volume')}
webcut volume {idVol2} with sheet extended from surface {idInt}  
${idVol3=Id('volume')}

find surface overlap volume {idVol2} {idVol3}  
${idF1=GroupMemberId('surf_overlap','surface',0)}
${idF2=GroupMemberId('surf_overlap','surface',1)}
surface {idF1} name 'fault1'


brick x {100*1000} y {80*1000} z {100*1000}   
${idVol4=Id('volume')}

webcut volume {idVol4} with sheet extended from surface {idSur}  
${idVol5=Id('volume')}

subtract volume {idVol2} {idVol3} from volume {idVol5} keep   #5中减去2 3
${idVol6=Id('volume')}

delete surface all     
delete volume {idVol1} {idVol4} {idVol5} 

imprint all   
merge all

volume all scheme TetMesh   
volume {idVol2} {idVol3} size {4.000000*1000}
mesh volume {idVol2} 
mesh volume {idVol3}
volume {idVol6} size {8.000000*1000}
mesh volume {idVol6} 
THex Volume all

volume all smooth scheme condition number beta 2.0 cpu 8 
smooth volume all
set unmerge Duplicate_mesh on
unmerge surface fault1 only
surface {idF2} name 'fault2'
unmerge curve 1

set node constraint off   
node in surface fault1 move normal to surface fault1 distance {-0.01*m} 
node in surface fault2 move normal to surface fault2 distance {-0.01*m}
compress all
set node constraint on   


`

**Comment by jpampuero** [comment]
What do you mean by "the module doesn't work"? What are the symptoms and error messages?

**Comment by jxhxb** [comment]
> What do you mean by "the module doesn't work"? What are the symptoms and error messages?

Hi jpampuero！There is no error message. I mean I got all the simulation results are the same as following picture, almost close to zero. I guess that the fault didn't slide !
![image](https://github.com/user-attachments/assets/a7a19cc4-93c4-4ff3-9352-c0d006ff6cef)
And the data' visualization in paraview is following:
![image](https://github.com/user-attachments/assets/fb4c3652-e95d-4bc2-b7a8-128af9e4cb95)


It should be expected to look similar to the image below：
![image](https://github.com/user-attachments/assets/aa3a8890-5994-451f-b2fe-8da53704cddf)

My question is : I didn't implement strike and dip angle loading in ‘HETE_fault_properties’.
Could you help me check initial_stress.dat,   DIST2D shapeval='rectangle',  &TWF   these three parameters  (they are in the top )in par_file_faults ? I just changed the position of them, and keep other parameters no change. I think that the positions (both in initial_stress.dat , DIST2D, TWF) after rotated are correct but I don't know the lx, ly and lc in"&DIST2D" should be change in which rule.

**Comment by jpampuero** [comment]
The fault can slip within a region with static friction coefficient of 0.63 that intersects a rectangular prism of dimensions lx, ly and lz. You need to modify the values of lx, ly and lz so that the prism does intersect the fault in the area you intend to break.

**Comment by jxhxb** [comment]
> The fault can slip within a region with static friction coefficient of 0.63 that intersects a rectangular prism of dimensions lx, ly and lz. You need to modify the values of lx, ly and lz so that the prism does intersect the fault in the area you intend to break.

Ok, i will try it now, thanks!
