### ISSUE TITLE
CMTSOLUTION_SOURCE

### ISSUE THREAD

**Issue by jxhxb** [SPECFEM/specfem3d#1739]
If i set the  Switches in Par_file‘ source part as following:
USE_SOURCES_RECEIVERS_Z         = .false.
USE_FORCE_POINT_SOURCE          = .false.
USE_RICKER_TIME_FUNCTION        = .true.
USE_EXTERNAL_SOURCE_FILE        = .false.
PRINT_SOURCE_TIME_FUNCTION      = .false.
USE_SOURCE_ENCODING             = .false.

and i make the parameters in CMTSOLUTION as these:
![image](https://github.com/user-attachments/assets/0812217a-818f-4115-a9c1-3e08ab5f0618)
this is a module with strike 0,dip 90, and i want to set 4 CMT-sources in a plane(3m.5m).

My questions are:
1: USE_RICKER_TIME_FUNCTION   = .true.  This  setting is working in CMTSOLUTION? If there is also the concept of 'dominate frequency'  ,and where to change it ?
2：What is the unit of half_duration? 
3：If i set the half_duration=80, the source function will be replaced by Guass_function?
4:Can i get the Green‘’ function through use CMTSOLUTION-source，and how to make it?

**Comment by jxhxb** [comment]
question :
1:What‘s the meaning of 'SXY_semd ’, is SXY_semd  used for calculate Green's function?

**Comment by danielpeter** [comment]
regarding the `USE_RICKER_TIME_FUNCTION` option, it is considered for both cases, force and CMT sources. turning this option on, the source will always use a Ricker wavelet. in your case, you specify the dominant frequency in the `half duration: ..`. in the example shown above, that's set to `80 Hz`.

for the strain seismograms, that was implemented by @homnath - you might reach out to him to get more details about what you see.

if you want to simulate Green's functions for a CMT source, you would use a single component CMT and a half duration of zero to mimick a Heaviside source time function.

**Comment by homnath** [comment]
Hi Jing Luo:

To elaborate on Daniel's response, there are two ways of computing the Green's functions depending on what you want or how you want to use them.

  1.
Set the unit value for each moment tensor component at a time (CMTSOLUTION), as Daniel suggested, and record the three displacement components of  (or velocity or acceleration). You need six simulations and store 6X3 =18 seismograms per station.
  2.
Set the unit value for each force component (FORCESOLUTION) and record the six strain components. You need three simulations and store 3X6 = 18 seismograms per station.

Best,
Hom Nath


---------------------------------------
Hom Nath Gharti, PhD
Assistant Professor | Digital Earth Scientist
https://www.digitalearthscience.com/
Department of Geological Sciences and Geological Engineering
Miller Hall 314, 36 Union St
Queen’s University
Kingston, ON K7L 3N6, Canada


Queen’s University is situated on traditional
Anishinaabe and Haudenosaunee Territory.<https://www.queensu.ca/encyclopedia/t/traditional-territories>
________________________________
