### ISSUE TITLE
MPI_INIT error in compiled SPECFEM3D 4.0.0 GPU version and also is new SPECFEM3D 4.1.1 GPU version during compilation

### ISSUE THREAD

**Issue by padesh** [SPECFEM/specfem3d#1740]
Hi team,

I had SPECFEM3D 4.0.0 GPU version compiled an year back and it was working fine till Tuesday (17th Sep). Suddenly it started giving  this error as soon as job for xmeshfem3D is submitted. I am using 4 GPU nodes ( 4 card each node) of V100s. I tried it with 1 and 2 nodes thinking is there any problem with MPI communicator across GPUs but it fails even on 1 node as well. It fails at xmeshfem3D  initiation itself and no output is produced. 

`srun $example_dir/bin/xmeshfem3D `

Part of error msg:

```
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /nfs/lebhomes07/dev2/fluentuser/alex_test/slurm_openmpi/OpenMPI/openmpi_4.0.5_linx64-Release/linx64/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
    mpi_init:startup:internal-failure

*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
***    and potentially your MPI job)
[g001:1853606] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[g002:1646624] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Now the path it is point to '/nfs/lebhomes07/dev2/fluentuser/alex_test/slurm_openmpi/OpenMPI/openmpi_4.0.5_linx64-Release/linx64/share/openmpi/help-mpi-runtime.txt' is not on the cluster on which I am running it. 

I thought to get the SPECFEM3D v4.1.1 version and compile it.  
Compilation command:

`./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-cuda=cuda9 CUDA_LIB=/sw/libs/cuda/12.2/lib64  --enable-vectorization`

The MPI part of the compilation again gives same error point to same path (./config output attached)

# MPI #

```
Cannot open configuration file /nfs/lebhomes07/dev2/fluentuser/alex_test/slurm_openmpi/OpenMPI/openmpi_4.0.5_linx64-Release/linx64/share/openmpi/mpif90-wrapper-data.txt
Error parsing data file mpif90: Not found
checking for mpi.h... no
configure: error: MPI header not found; try setting MPI_INC.

```

Same path here too `/nfs/lebhomes07/dev2/fluentuser/alex_test/slurm_openmpi/OpenMPI/openmpi_4.0.5_linx64-Release/linx64/share/openmpi

Not sure whats wrong and how to fix this. Since the path it is pointing to is not part of the cluster I am running this, is this is a problem in the source code? But then, why the compiled version I had been using since an year and was working fine till 2 days back suddenly started to give this MPI_Init problem as well.

Attached are error file (running 4.0.0) and config output on compiling 4.1.1

[Config output.txt](https://github.com/user-attachments/files/17063580/Config.output.txt)
[error.txt](https://github.com/user-attachments/files/17063581/error.txt)
. 
Any help is highly appreciated.

Thanks.

**Comment by danielpeter** [comment]
there was likely a change on your system rather than in SPECFEM3D. 

did you try setting MPI_INC as suggested by the configuration script?

**Comment by padesh** [comment]
Yes, there is a bug in OpenMPI 4.1.4 that is causing this. But resolved now from system admin. Closing this. 

Thanks for your reply.

**Comment by padesh** [comment]
Bug in OpenMPI 4.1.4 causing this.
