### ISSUE TITLE
CMTSOLUTION_time shift

### ISSUE THREAD

**Issue by jxhxb** [SPECFEM/specfem3d#1754]
if the CMTSOLUTION source_time_fuction is ricker_time_function，like the following set, i set time shift =0.04:
![image](https://github.com/user-attachments/assets/4e5ea5d4-928a-4541-bb74-ca48f5667519)
and the ricker_time_function in OUTPUT_FILES's figure is this:
![image](https://github.com/user-attachments/assets/4dfd164c-7542-4bee-98b2-cd33ced1a328)
I have two questions:
1: In forward simulation, the source_time_function will start at t=0.0?
2:Add the basis  :when time_shift=0.0, the source_time_function is this :
![image](https://github.com/user-attachments/assets/a037c19a-5e2b-4999-855a-e143dd384ec5)
Why there is no change about 'time shift=0.04'.

All the question above are to solve the problem: I guess i got a wrong record-wave, i think the reason is source_time_function' time_shift:
![image](https://github.com/user-attachments/assets/736a1790-dfa2-457e-8151-93539a2e33eb)

**Comment by jxhxb** [comment]
I  want to make the source time function start at t>=0.0, and then try it again.

**Comment by danielpeter** [comment]
the time shift of the source will only be considered if multiple sources are specified in the CMTSOLUTION file (with at least one source having a zero time shift). in those cases, it is important that the relative time differences between sources is accounted for and time shift info makes sense. having only 1 CMT source, the shift is ignored and always set to zero. The shift would only adapt the CMT origin time of the source if the output is in ASDF format.

for the SPECFEM simulations, the source wavelet is always centered at time 0.0. the simulation start time (t0) is then chosen such that the initial source strength is very close to zero. this avoids high-frequency wave artifacts that would occur if your wave simulation would start with a strong initial source acceleration offset at the source grid points. 

if you want your traces to start at time 0, then you could write your own small script and shift the time values accordingly.
