### ISSUE TITLE
Some questions about full waveform inversion

### ISSUE THREAD

**Issue by zuoxuan-de** [SPECFEM/specfem3d#1757]
I'm trying to use specfem3d for some full waveform inversion tasks, but I have some usage questions that I would like your help with. Here are my questions: 1. Can I have each gun with its own different observing system when I do the inversion. 2. Will the other functional modules in it work properly, such as multi-scale inversion, regularization, etc.

**Comment by carltape** [comment]
I would suggest posting this discussion in the adjtomo realm. Specfem has been integrated into many different FWI (adjoint tomography) workflows. My impression is that the most actively maintained version is within the [adjtomo](https://github.com/adjtomo) organization. And try to make the questions as precise as possible.

**Comment by zuoxuan-de** [comment]
thank you
