### ISSUE TITLE
🐛 [BUG] - <title>At the start of use

### ISSUE THREAD

**Issue by Seisstudnet** [SPECFEM/specfem3d#1758]
### Description

This is my first time to use SPECFEM3D. I want to run EXAMPLES/benchmarks/attenuation/viscoelastic/run_this_example.sh, but its error is "ln: failed to create symbolic link './xmeshfem3D': Operation not permitted", includes ./xgenerate_databases and ./xspecfem3D. How can I solve this problem?

### Affected SPECFEM3D version

the newest 

### Your software and hardware environment

ubuntu 22.04

### Reproduction steps

```bash
in file "EXAMPLES/benchmarks/attenuation/viscoelastic" then "./run_this_example.sh"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by mnagaso** [comment]
Hi,

It must be the problem on the permission of where you are trying to create the symlinks of bin contents. So please check that around.
It should not be marked as bug.

**Comment by Seisstudnet** [comment]
> Hi,
> 
> It must be the problem on the permission of where you are trying to create the symlinks of bin contents. So please check that around. It should not be marked as bug.

Thank you for your reply. It's really not a bug, it's that I didn't change the title. I'll check my use of it based on your suggestions. By the way, I have carefully adhered to the steps outlined for the SPECFEM3D installation. I am optimistic that everything should be functioning as intended. I'll try to improve it. Thank you so much！

**Comment by mnagaso** [comment]
No problem! Probably, you can at first check if `xspecfem3D` etc. are created in your specfem3d/bin directory after compilation. Then you can also check if the command `ln -s ../../../../../bin/xmeshfem3D .` in your example directory `EXAMPLES/benchmarks/attenuation/viscoelastic/` to check if you will have the same error.
