### ISSUE TITLE
🐛 [BUG] - <title>Suspected error in combine_vol_data.F90

### ISSUE THREAD

**Issue by eyalshimony** [SPECFEM/specfem3d#1760]
### Description

In the file combine_vol_data.F90, the following definition appears in lines 634, 863:
real(kind=CUSTOM_REAL),dimension(NGLLY,NGLLY,NGLLZ,NSPEC_AB),intent(in) :: data
I suspect that it should be NGLLX,NGLLY and not NGLLY,NGLLY.

### Affected SPECFEM3D version

latest development version

### Your software and hardware environment

inapplicable

### Reproduction steps

```bash
Problem in code
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by danielpeter** [comment]
hi Eyal, good catch! ... and there's probably the same bug on line 863 in that file. would you mind submitting a pull request with a fix for those two lines?

**Comment by eyalshimony** [comment]
Sure, I will do it
